//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROVAL
    {
        public string approvalCode { get; set; }
        public System.DateTime approvalFrom { get; set; }
        public System.DateTime approvalUntil { get; set; }
        public string approvalPersonId { get; set; }
        public int approvalNumber { get; set; }
    
        public virtual APPROVALTYPE APPROVALTYPE { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
