//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeforeTelephone
    {
        public string beforeTelephone1 { get; set; }
    }
}
