//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.APPROVALS = new HashSet<APPROVAL>();
            this.VEHICLES = new HashSet<VEHICLE>();
        }
    
        public string personId { get; set; }
        public string personFirstName { get; set; }
        public string personLastName { get; set; }
        public string personBeforeTelephone { get; set; }
        public string personTelephone { get; set; }
        public string personBeforeCellphone { get; set; }
        public string personCellphone { get; set; }
        public int personCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPROVAL> APPROVALS { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE> VEHICLES { get; set; }
    }
}
