//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public string studentId { get; set; }
        public string studentFacultyCode { get; set; }
        public int studentYear { get; set; }
        public int studentType { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
